package org.eumetsat.Utils.Common;

import java.io.IOException;
import java.util.HashMap;

import org.apache.log4j.Logger;

public class Constants
{
   static Logger log = Logger.getLogger( Constants.class );
   
   public static final String SEP = "/";
   public static final String SPC = " ";
   public static final String DOT = ".";
   public static final String EQUALS = "=";
   public static final String QUOTE = "\"";
   public static final String US = "_";
   public static final String MINUS = "-";
   public static final String PLUS = "+";
   public static final String ZERO = "0";
   public static final String COLON = ":";
   
   public static final String LEFT_BRACKET = "<";
   public static final String RIGHT_BRACKET = ">";
   public static final String TAG_END = "/>";
   public static final String START_TAG_END = "</";
   
   public static final String SAX_VALIDATION_STR = "http://xml.org/sax/features/validation";
   public static final boolean DEFAULT_VALIDATE_DOC = true;
   
   public static final String LOG4J_DEFAULT_FILENAME = "/log4j.properties";
   public static final String PRODUCT_TYPES_FILENAME = "/productTypes.xml";
   
   public static final String UNIDATA_CONFIG_SWITCH = "nj22Config";
   public static final String INSTALLED_DIR_SWITCH = "installedDir";
   
   public static final String GEN_WMO_FILENAME = "Gen_WMO_Filename";
   
   public static final String GENERIC_FRAMEWORK_IDENTIFIER = "<!-- THIS FILE WAS GENERATED BY THE EUMETSAT GSICS PRODUCT NETCDF FRAME WORK -->";
   public static final String GENERIC_FRAMEWORK_FILE_PREFIX = "EUM_GSICS_";
   
   public static final String CONFIG_DIR = "/config";
   public static final String DATA_DIR = "/data";
   
   public static final boolean DEBUG_ON = false;
   public static final boolean CREATE_STUBS = false;
   
   public static final String REPLACEMENT_STRING = "XXXXX";
   
   public static final String LICENSE = "CopyRight EUMETSAT";
   public static final String AGENCY = "EUMETSAT";
   
   public static final String NCML_SUFFIX = "ncml";
   
   public static final String TAG_DIMENSIONS = "dimension";
   public static final String TAG_ATTRIBUTES = "attribute";
   
   public static final String READ_DATA_FUNCTION_ATTR = "function_to_read_data";   
   public static final String CALL_PROD_FUNCTION_ATTR = "function_call_product_func";
   public static final String COPY_DATA_FUNCTION_ATTR = "function_direct_string_copy";
   public static final String DEFAULT_FUNCTION_VALUE = "default";
   public static final String PRODUCT_FUNC_PREFIX = "get_";

   public static final String ATTR_NAME = "name";
   public static final String ATTR_VALUE = "value";
   public static final String ATTR_FUNC = "func";
   public static final String ATTR_LENGTH = "length";
   
   public static final String FILE_PREFIX_STR = "file:";
   
   public static final short NO_VALUE = 0;
   
   public static final String NOT_INITIALISED_STR = "EMPTY";
   public static final String NOT_SET_STR = "NA";
   public static final String DEFAULT_RE = ".*";
   
   public static final int DOES_NOT_OCCUR = -1;
   public static final int IS_NOT_SET = -1;
   
   public static final int UNKNOWN_FILE_TYPE = -1;
   
   public static final int XML_FILE = 0;
   public static final int XSL_FILE = 1;
   public static final int XSD_FILE = 2;
   public static final int NCML_FILE = 3;
   public static final int DATA_FILE = 4;
   public static final int TEXT_FILE = 5;
   public static final int TPL_FILE = 6;
   public static final int NAT_FILE = 7;
   public static final int BUFR_FILE = 8;
   public static final int GRIB_FILE = 9;
   public static final int NETCDF_FILE = 10;

   public static final String XML_EXT_STR = ".xml";
   public static final String XSL_EXT_STR = ".xsl";
   public static final String XSD_EXT_STR = ".xsd";
   public static final String NCML_EXT_STR = ".ncml";
   public static final String DATA_EXT_STR = ".dat";
   public static final String TEXT_EXT_STR = ".txt";
   public static final String TPL_EXT_STR = ".tpl";
   public static final String NAT_EXT_STR = ".nat";
   public static final String BUFR_EXT_STR = ".bufr";
   public static final String GRIB_EXT_STR = ".grib";
   public static final String NETCDF_EXT_STR = ".ncml";
   
   public static HashMap<String, Integer> fileTypes = new HashMap<String, Integer>( );   

   static
   {
      fileTypes.put( XML_EXT_STR, XML_FILE );
      fileTypes.put( XSL_EXT_STR, XSL_FILE );
      fileTypes.put( XSD_EXT_STR, XSD_FILE );
      fileTypes.put( NCML_EXT_STR, NCML_FILE );
      fileTypes.put( DATA_EXT_STR, DATA_FILE );
      fileTypes.put( TEXT_EXT_STR, TEXT_FILE );
      fileTypes.put( TPL_EXT_STR, TPL_FILE );
      fileTypes.put( NAT_EXT_STR, NAT_FILE );
      fileTypes.put( BUFR_EXT_STR, BUFR_FILE );
      fileTypes.put( GRIB_EXT_STR, GRIB_FILE );
      fileTypes.put( NETCDF_EXT_STR, NETCDF_FILE );
   };
   
   public static final String IOSP_HELPER_ATTR_PLACEHOLDER = "<!-- IOSP Helper Attributes -->";
   
   public static final String PRODUCT_IDENT_HELPER = "helper_product_identities";
   public static final String PRODUCT_NAME_HELPER = "helper_product_name";
   public static final String SOURCE_FILE_HELPER = "helper_source_filename";
   public static final String NCML_FILE_HELPER = "helper_ncml_filename";
   public static final String PRODUCT_CLASS_FILE_HELPER = "helper_product_class";
   
   public static final String[ ] ncmlHelpers =
   {
      PRODUCT_IDENT_HELPER,
      PRODUCT_NAME_HELPER,
      SOURCE_FILE_HELPER,
      NCML_FILE_HELPER,
      PRODUCT_CLASS_FILE_HELPER,
      null
   };
   
   public static HashMap<String, Short> helperAttribute = new HashMap<String, Short>( );
   
   public static final String METOPA_STR = "MetOp-A";
   public static final String MO2_STR = "M02";
   
   public static final String METOPB_STR = "MetOp-B";
   public static final String MO1_STR = "M01";
   
   public static final String NOAA19_STR = "NOAA19";
   public static final String N19_STR = "N19";
   
   public static HashMap<String, String> satelliteNames = new HashMap<String, String>( );
   
   static
   {
      short indx = 0;
      
      while ( ncmlHelpers[ indx ] != null )
      {
         helperAttribute.put( ncmlHelpers[ indx ], indx );
         indx++;
      }
      
      satelliteNames.put( MO2_STR, METOPA_STR );
      satelliteNames.put( MO1_STR, METOPB_STR );
      satelliteNames.put( N19_STR, NOAA19_STR );
   };
   
   /**
    * Define some flag values for EPS data sets.
    */
   public static enum EPS_HEADER 
   {
      MPHR( Byte.parseByte( "1" ), Byte.parseByte( "0" ) ),
      SPHR( Byte.parseByte( "2" ), Byte.parseByte( "0" ) ),
      IPR( Byte.parseByte( "3" ), Byte.parseByte( "0" ) ),
      GEADR( Byte.parseByte( "4" ), Byte.parseByte( "8" ) ),
      GIADR( Byte.parseByte( "5" ), Byte.parseByte( "8" ) ),
      VEADR( Byte.parseByte( "6" ), Byte.parseByte( "8" ) ),
      VIADR( Byte.parseByte( "7" ), Byte.parseByte( "8" ) ),
      MDR( Byte.parseByte( "8" ), Byte.parseByte( "8" ) ),
      DMDR( Byte.parseByte( "8" ), Byte.parseByte( "13" ) );
      
      private byte value;
      private byte subvalue;
      
      EPS_HEADER( byte  value, byte subvalue ) 
      {
         this.value = value;
         this.subvalue = subvalue;
      }
      public byte getValue( ) 
      {
         return this.value;
      }
      public byte getSubvalue( ) 
      {
         return this.subvalue;
      }
   };
   
   public static final String PRODUCT_IDENT_ATTR_XML = "<attribute name=\"" + PRODUCT_IDENT_HELPER + "\" value=\"NA\" />";
   public static final String PRODUCT_NAME_ATTR_XML = "<attribute name=\"" + PRODUCT_NAME_HELPER + "\" value=\"NA\" />";
   public static final String SOURCE_FILE_ATTR_XML = "<attribute name=\"" + SOURCE_FILE_HELPER + "\" value=\"NA\" />";
   public static final String PRODUCT_NCML_FILE_ATTR_XML = "<attribute name=\"" + NCML_FILE_HELPER + "\" value=\"NA\" />";
   public static final String PRODUCT_CLASS_ATTR_XML = "<attribute name=\"" + PRODUCT_CLASS_FILE_HELPER + "\" value=\"NA\" />";
   
   // EPS GFS fieldnames.
   public static final String PRODUCT_NAME_STR = "PRODUCT_NAME";
   public static final String PARENT_PRODUCT_NAME_1_STR = "PARENT_PRODUCT_NAME_1";
   public static final String PARENT_PRODUCT_NAME_2_STR = "PARENT_PRODUCT_NAME_2";
   public static final String PARENT_PRODUCT_NAME_3_STR = "PARENT_PRODUCT_NAME_3";
   public static final String PARENT_PRODUCT_NAME_4_STR = "PARENT_PRODUCT_NAME_4";
   public static final String INSTRUMENT_ID_STR = "INSTRUMENT_ID";
   public static final String INSTRUMENT_MODEL_STR = "sensor_model";
   public static final String PRODUCT_TYPE_STR = "PRODUCT_TYPE";
   public static final String PROCESSING_LEVEL_STR = "PROCESSING_LEVEL";
   public static final String SPACECRAFT_ID_STR = "SPACECRAFT_ID";
   public static final String SENSING_START_STR = "SENSING_START";
   public static final String SENSING_END_STR = "SENSING_END";
   public static final String SENSING_START_THEORETICAL_STR = "SENSING_START_THEORETICAL";
   public static final String SENSING_END_THEORETICAL_STR = "SENSING_END_THEORETICAL";
   public static final String PROCESSING_CENTRE_STR = "PROCESSING_CENTRE";
   public static final String PROCESSOR_MAJOR_VERSION_STR = "PROCESSOR_MAJOR_VERSION";
   public static final String PROCESSOR_MINOR_VERSION_STR = "PROCESSOR_MINOR_VERSION";
   public static final String FORMAT_MAJOR_VERSION_STR = "FORMAT_MAJOR_VERSION";
   public static final String FORMAT_MINOR_VERSION_STR = "FORMAT_MINOR_VERSION";
   public static final String PROCESSING_TIME_START_STR = "PROCESSING_TIME_START";
   public static final String PROCESSING_TIME_END_STR = "PROCESSING_TIME_END";
   public static final String PROCESSING_MODE_STR = "PROCESSING_MODE";
   public static final String DISPOSITION_MODE_STR = "DISPOSITION_MODE";
   public static final String RECEIVING_GROUND_STATION_STR = "RECEIVING_GROUND_STATION";
   public static final String RECEIVE_TIME_START_STR = "RECEIVE_TIME_START";
   public static final String RECEIVE_TIME_END_STR = "RECEIVE_TIME_END";
   public static final String ORBIT_START_STR = "ORBIT_START";
   public static final String ORBIT_END_STR = "ORBIT_END";
   public static final String ACTUAL_PRODUCT_SIZE_STR = "ACTUAL_PRODUCT_SIZE";
   public static final String STATE_VECTOR_TIME_STR = "STATE_VECTOR_TIME";
   public static final String SEMI_MAJOR_AXIS_STR = "SEMI_MAJOR_AXIS";
   public static final String ECCENTRICITY_STR = "ECCENTRICITY";
   public static final String INCLINATION_STR = "INCLINATION";
   public static final String PERIGEE_ARGUMENT_STR = "PERIGEE_ARGUMENT";
   public static final String RIGHT_ASCENSION_STR = "RIGHT_ASCENSION";
   public static final String MEAN_ANOMALY_STR = "MEAN_ANOMALY";
   public static final String X_POSITION_STR = "X_POSITION";
   public static final String Y_POSITION_STR = "Y_POSITION";
   public static final String Z_POSITION_STR = "Z_POSITION";
   public static final String X_VELOCITY_STR = "X_VELOCITY";
   public static final String Y_VELOCITY_STR = "Y_VELOCITY";
   public static final String Z_VELOCITY_STR = "Z_VELOCITY";
   public static final String EARTH_SUN_DISTANCE_RATIO_STR = "EARTH_SUN_DISTANCE_RATIO";
   public static final String LOCATION_TOLERANCE_RADIAL_STR = "LOCATION_TOLERANCE_RADIAL";
   public static final String LOCATION_TOLERANCE_CROSSTRACK_STR = "LOCATION_TOLERANCE_CROSSTRACK";
   public static final String LOCATION_TOLERANCE_ALONGTRACK_STR = "LOCATION_TOLERANCE_ALONGTRACK";
   public static final String YAW_ERROR_STR = "YAW_ERROR";
   public static final String ROLL_ERROR_STR = "ROLL_ERROR";
   public static final String PITCH_ERROR_STR = "PITCH_ERROR";
   public static final String SUBSAT_LATITUDE_START_STR = "SUBSAT_LATITUDE_START";
   public static final String SUBSAT_LONGITUDE_START_STR = "SUBSAT_LONGITUDE_START";
   public static final String SUBSAT_LATITUDE_END_STR = "SUBSAT_LATITUDE_END";
   public static final String SUBSAT_LONGITUDE_END_STR = "SUBSAT_LONGITUDE_END";
   public static final String LEAP_SECOND_STR = "LEAP_SECOND";
   public static final String LEAP_SECOND_UTC_STR = "LEAP_SECOND_UTC";
   public static final String TOTAL_RECORDS_STR = "TOTAL_RECORDS";
   public static final String TOTAL_MPHR_STR = "TOTAL_MPHR";
   public static final String TOTAL_SPHR_STR = "TOTAL_SPHR";
   public static final String TOTAL_IPR_STR = "TOTAL_IPR";
   public static final String TOTAL_GEADR_STR = "TOTAL_GEADR";
   public static final String TOTAL_GIADR_STR = "TOTAL_GIADR";
   public static final String TOTAL_VEADR_STR = "TOTAL_VEADR";
   public static final String TOTAL_VIADR_STR = "TOTAL_VIADR";
   public static final String TOTAL_MDR_STR = "TOTAL_MDR";
   public static final String COUNT_DEGRADED_INST_MDR_STR = "COUNT_DEGRADED_INST_MDR";
   public static final String COUNT_DEGRADED_PROC_MDR_STR = "COUNT_DEGRADED_PROC_MDR";
   public static final String COUNT_DEGRADED_INST_MDR_BLOCKS_STR = "COUNT_DEGRADED_INST_MDR_BLOCKS";
   public static final String COUNT_DEGRADED_PROC_MDR_BLOCKS_STR = "COUNT_DEGRADED_PROC_MDR_BLOCKS";
   public static final String DURATION_OF_PRODUCT_STR = "DURATION_OF_PRODUCT";
   public static final String MILLISECONDS_OF_DATA_PRESENT_STR = "MILLISECONDS_OF_DATA_PRESENT";
   public static final String MILLISECONDS_OF_DATA_MISSING_STR = "MILLISECONDS_OF_DATA_MISSING";
   public static final String SUBSETTED_PRODUCT_STR = "SUBSETTED_PRODUCT";
   public static final String N_L1A_MDR_STR = "N_L1A_MDR";
   public static final String N_L1A_MDR_B0_STR = "N_L1A_MDR_B0";
   public static final String N_L1A_MDR_B1_STR = "N_L1A_MDR_B1";
   public static final String N_L1A_MDR_B2_STR = "N_L1A_MDR_B2";
   public static final String N_L1A_MDR_B3_STR = "N_L1A_MDR_B3";
   public static final String N_L1A_MDR_B4_STR = "N_L1A_MDR_B4";
   public static final String N_L1A_MDR_B5_STR = "N_L1A_MDR_B5";
   public static final String N_GAPS_STR = "N_GAPS";
   public static final String TOTAL_GAPS_SIZE_STR = "TOTAL_GAPS_SIZE";
   public static final String N_HKTM_PACKETS_RECEIVED_STR = "N_HKTM_PACKETS_RECEIVED";
   public static final String N_F_ECHO_STR = "N_F_ECHO";
   public static final String N_M_ECHO_STR = "N_M_ECHO";
   public static final String N_C_ECHO_STR = "N_C_ECHO";
   public static final String N_I_ECHO_STR = "N_I_ECHO";
   public static final String N_F_NOISE_STR = "N_F_NOISE";
   public static final String N_M_NOISE_STR = "N_M_NOISE";
   public static final String N_C_NOISE_STR = "N_C_NOISE";
   public static final String N_I_NOISE_STR = "N_I_NOISE";
   public static final String N_F_PG_STR = "N_F_PG";
   public static final String N_V_PG_STR = "N_V_PG";
   public static final String N_F_EXT_PG_STR = "N_F_EXT_PG";
   public static final String N_F_FILTER_STR = "N_F_FILTER";
   public static final String N_V_FILTER_STR = "N_V_FILTER";
   public static final String N_F_EXT_FILTER_STR = "N_F_EXT_FILTER";
   public static final String N_F_TEL_FILTER_STR = "N_F_TEL_FILTER";
   public static final String N_F_ORBIT_STR = "N_F_ORBIT";
   public static final String N_F_ATTITUDE_STR = "N_F_ATTITUDE";
   public static final String N_F_OMEGA_STR = "N_F_OMEGA";
   public static final String N_F_MAN_STR = "N_F_MAN";
   public static final String N_F_DSL_STR = "N_F_DSL";
   public static final String N_F_E_TEL_PRES_STR = "N_F_E_TEL_PRES";
   public static final String N_F_E_TEL_IR_STR = "N_F_E_TEL_IR";
   public static final String N_F_CE_STR = "N_F_CE";
   public static final String N_V_CE_STR = "N_V_CE";
   public static final String N_F_OA_STR = "N_F_OA";
   public static final String N_F_TEL_STR = "N_F_TEL";
   public static final String N_F_SA_STR = "N_F_SA";
   public static final String N_F_LAND_STR = "N_F_LAND";
   public static final String N_L1B_MDR_STR = "N_L1B_MDR";
   public static final String N_EMPTY_S0_TRIP_STR = "N_EMPTY_S0_TRIP";
   public static final String N_L1B_MDR_F_STR = "N_L1B_MDR_F";
   public static final String N_EMPTY_S0_TRIP_F_STR = "N_EMPTY_S0_TRIP_F";
   public static final String N_L1B_MDR_M_STR = "N_L1B_MDR_M";
   public static final String N_EMPTY_S0_TRIP_M_STR = "N_EMPTY_S0_TRIP_M";
   public static final String N_L1B_MDR_A_STR = "N_L1B_MDR_A";
   public static final String N_EMPTY_S0_TRIP_A_STR = "N_EMPTY_S0_TRIP_A";
   public static final String N_F_KP_F_STR = "N_F_KP_F";
   public static final String N_F_USABLE_F_STR = "N_F_USABLE_F";
   public static final String AVG_F_F_F_STR = "AVG_F_F_F";
   public static final String AVG_F_V_F_STR = "AVG_F_V_F";
   public static final String AVG_F_OA_F_STR = "AVG_F_OA_F";
   public static final String AVG_F_SA_F_STR = "AVG_F_SA_F";
   public static final String AVG_F_TEL_F_STR = "AVG_F_TEL_F";
   public static final String AVG_F_EXT_FIL_F_STR = "AVG_F_EXT_FIL_F";
   public static final String AVG_F_LAND_F_STR = "AVG_F_LAND_F";
   public static final String N_F_KP_M_STR = "N_F_KP_M";
   public static final String N_F_USABLE_M_STR = "N_F_USABLE_M";
   public static final String AVG_F_F_M_STR = "AVG_F_F_M";
   public static final String AVG_F_V_M_STR = "AVG_F_V_M";
   public static final String AVG_F_OA_M_STR = "AVG_F_OA_M";
   public static final String AVG_F_SA_M_STR = "AVG_F_SA_M";
   public static final String AVG_F_TEL_M_STR = "AVG_F_TEL_M";
   public static final String AVG_F_EXT_FIL_M_STR = "AVG_F_EXT_FIL_M";
   public static final String AVG_F_LAND_M_STR = "AVG_F_LAND_M";
   public static final String N_F_KP_A_STR = "N_F_KP_A";
   public static final String N_F_USABLE_A_STR = "N_F_USABLE_A";
   public static final String AVG_F_F_A_STR = "AVG_F_F_A";
   public static final String AVG_F_V_A_STR = "AVG_F_V_A";
   public static final String AVG_F_OA_A_STR = "AVG_F_OA_A";
   public static final String AVG_F_SA_A_STR = "AVG_F_SA_A";
   public static final String AVG_F_TEL_A_STR = "AVG_F_TEL_A";
   public static final String AVG_F_EXT_FIL_A_STR = "AVG_F_EXT_FIL_A";
   public static final String AVG_F_LAND_A_STR = "AVG_F_LAND_A";
   public static final String PROCESSING_MESSAGE_1_STR = "PROCESSING_MESSAGE_1";
   public static final String PROCESSING_MESSAGE_2_STR = "PROCESSING_MESSAGE_2";
   
   public static final ClassNotFoundException CLASS_NOT_FOUND_EXP = new ClassNotFoundException( );
   public static final IOException IO_EXP = new IOException( );
   public static final Exception EXP = new Exception( );
   public static final IllegalArgumentException iExp = new IllegalArgumentException( );
   
   /**
    * Constructor
    */
   public Constants( )
   {
   }
   
   /**
    * COMGetLicenseString - Get the license string for all EUMETSAT NetCDF formats.
    * @return
    */
   public static String COMGetLicenseString( )
   {
      String yearStr = IOUtils.getYearStr( );
      
      return( LICENSE + SPC + yearStr );
   }
   
   
}
